#!/usr/bin/env bash

# Credit to ThePrimeagen

# Define an array of frequently accessed directories
frequent_directories=(
    ~/Downloads/vim-tutorial
    /tmp
    # Add more directories here
)

# Check if a directory path is provided as an argument.
if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Use fzf to interactively select a directory from the array
    selected=$(printf '%s\n' "${frequent_directories[@]}" | fzf)
fi

# Ensure a directory is selected
if [ -z "$selected" ]; then
    echo "No directory selected. Exiting."
    exit 1
fi

# Modify the selected directory name to be used as the tmux session name.
dirname=$(basename "$selected" | sed 's/\./_/g')

# Check if a tmux session with the same name exists. If it does, switch to it.
tmux switch-client -t =$dirname 

# If the session switch was successful, exit the script.
if [[ $? -eq 0 ]]; then
    exit 0
fi

# If the session doesn't exist, create it and switch to it.
tmux new-session -c "$selected" -d -s "$dirname" && tmux switch-client -t "$dirname" || tmux new -c "$selected" -A -s "$dirname"

